<a href="https://colab.research.google.com/github/PriyanshuChaudhary00/Ai/blob/main/simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [223]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset , DataLoader

In [224]:
!ls
file = "./100_Unique_QA_Dataset.csv"

100_Unique_QA_Dataset.csv  sample_data

In [225]:
import pandas as pd

In [226]:
df = pd.read_csv(file)
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [227]:
df.loc[0]

question    What is the capital of France?
answer                               Paris
Name: 0, dtype: object

In [228]:
def tokenize(text):
  text = text.lower()
  text = text.replace("?" , "")
  text = text.replace("'" , "")
  return text.split()

In [229]:
tokenize("What is the capital of France?")

['what', 'is', 'the', 'capital', 'of', 'france']

In [230]:
def build_vocab(row):
  token_ques = tokenize(row["question"])
  token_ans = tokenize(row['answer'])

  merge_token = token_ans+token_ques
  # print(merge_token)

  for token in merge_token:
    if token in vocab :
      pass
    else :
      vocab[token] = len(vocab)

In [231]:
vocab = {"<unk>":0}

In [232]:
df.apply(build_vocab , axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [233]:
len(vocab)

324

In [234]:
def text_to_index(text , vocab):
  indexed_text = []

  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else :
      indexed_text.append(vocab["<unk>"])
  return indexed_text

In [235]:
ind = text_to_index("What is the capital of France?" , vocab)
print(ind)

[2, 3, 4, 5, 6, 7]

In [236]:
class QA_dataset(Dataset):
  def __init__(self , df , vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self , index):
    ques = text_to_index(self.df.iloc[index]["question"], self.vocab)
    ans = text_to_index(self.df.iloc[index]["answer"], self.vocab)
    return torch.tensor(ques) , torch.tensor(ans)

In [237]:
dataset = QA_dataset(df , vocab)
dataset[0]

(tensor([2, 3, 4, 5, 6, 7]), tensor([1]))

In [238]:
loaded_data = DataLoader(dataset , batch_size=1 , shuffle=True)

In [239]:
class simpleRNN(nn.Module):
  def __init__(self , vocab_size):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size , 50 )
    self.rnn = nn.RNN(50 , 64 , batch_first=True)
    self.fc = nn.Linear(64 , vocab_size)
  def forward(self , x):
    em = self.embedding(x)
    rnn = self.rnn(em)
    y_hat = self.fc(rnn[1])

    return y_hat

In [240]:
model = simpleRNN(len(vocab))

In [241]:
learning_rate = 0.001
epoch = 200

In [242]:
optimizer = optim.Adam(model.parameters() , lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

In [243]:
for epoch in range(epoch):
  total_loss = 0

  for i , (input , target) in enumerate(loaded_data):
    optimizer.zero_grad()

    output = model(input)
    # print(output.shape)

    output = output.squeeze(1)
    target = target.squeeze(1)
    loss = loss_fn(output , target)

    loss.backward()

    optimizer.step()

    total_loss += loss.item()
  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 522.943436
Epoch: 2, Loss: 455.698061
Epoch: 3, Loss: 378.254727
Epoch: 4, Loss: 313.106366
Epoch: 5, Loss: 259.696373
Epoch: 6, Loss: 211.227808
Epoch: 7, Loss: 167.723191
Epoch: 8, Loss: 129.921277
Epoch: 9, Loss: 99.715418
Epoch: 10, Loss: 76.428889
Epoch: 11, Loss: 58.681265
Epoch: 12, Loss: 45.941987
Epoch: 13, Loss: 36.623060
Epoch: 14, Loss: 29.593614
Epoch: 15, Loss: 24.333709
Epoch: 16, Loss: 20.531407
Epoch: 17, Loss: 17.188095
Epoch: 18, Loss: 14.614212
Epoch: 19, Loss: 12.556836
Epoch: 20, Loss: 10.897392
Epoch: 21, Loss: 9.535253
Epoch: 22, Loss: 8.449357
Epoch: 23, Loss: 7.488062
Epoch: 24, Loss: 6.668076
Epoch: 25, Loss: 5.982523
Epoch: 26, Loss: 5.407035
Epoch: 27, Loss: 4.891356
Epoch: 28, Loss: 4.450619
Epoch: 29, Loss: 4.049829
Epoch: 30, Loss: 3.726102
Epoch: 31, Loss: 3.424234
Epoch: 32, Loss: 3.144903
Epoch: 33, Loss: 2.911836
Epoch: 34, Loss: 2.691647
Epoch: 35, Loss: 2.496448
Epoch: 36, Loss: 2.314758
Epoch: 37, Loss: 2.157596
Epoch: 38, Loss: 2.009633
Epoch: 39, Loss: 1.875745
Epoch: 40, Loss: 1.753763
Epoch: 41, Loss: 1.641731
Epoch: 42, Loss: 1.541914
Epoch: 43, Loss: 1.443717
Epoch: 44, Loss: 1.355475
Epoch: 45, Loss: 1.273836
Epoch: 46, Loss: 1.198663
Epoch: 47, Loss: 1.128999
Epoch: 48, Loss: 1.062901
Epoch: 49, Loss: 1.003436
Epoch: 50, Loss: 0.947587
Epoch: 51, Loss: 0.894040
Epoch: 52, Loss: 0.844948
Epoch: 53, Loss: 0.798699
Epoch: 54, Loss: 0.755576
Epoch: 55, Loss: 0.715152
Epoch: 56, Loss: 0.677265
Epoch: 57, Loss: 0.642050
Epoch: 58, Loss: 0.608214
Epoch: 59, Loss: 0.576408
Epoch: 60, Loss: 0.546878
Epoch: 61, Loss: 0.519188
Epoch: 62, Loss: 0.492124
Epoch: 63, Loss: 0.467479
Epoch: 64, Loss: 0.444741
Epoch: 65, Loss: 0.422164
Epoch: 66, Loss: 0.401589
Epoch: 67, Loss: 0.381577
Epoch: 68, Loss: 0.363236
Epoch: 69, Loss: 0.345223
Epoch: 70, Loss: 0.328298
Epoch: 71, Loss: 0.312370
Epoch: 72, Loss: 0.297460
Epoch: 73, Loss: 0.283407
Epoch: 74, Loss: 0.269593
Epoch: 75, Loss: 0.256931
Epoch: 76, Loss: 0.244453
Epoch: 77, Loss: 0.233032
Epoch: 78, Loss: 0.221827
Epoch: 79, Loss: 0.211669
Epoch: 80, Loss: 0.201621
Epoch: 81, Loss: 0.192207
Epoch: 82, Loss: 0.183147
Epoch: 83, Loss: 0.174873
Epoch: 84, Loss: 0.166732
Epoch: 85, Loss: 0.158804
Epoch: 86, Loss: 0.151588
Epoch: 87, Loss: 0.144710
Epoch: 88, Loss: 0.138028
Epoch: 89, Loss: 0.131635
Epoch: 90, Loss: 0.125628
Epoch: 91, Loss: 0.119913
Epoch: 92, Loss: 0.114500
Epoch: 93, Loss: 0.109198
Epoch: 94, Loss: 0.104307
Epoch: 95, Loss: 0.099648
Epoch: 96, Loss: 0.095032
Epoch: 97, Loss: 0.090737
Epoch: 98, Loss: 0.086626
Epoch: 99, Loss: 0.082724
Epoch: 100, Loss: 0.079104
Epoch: 101, Loss: 0.075506
Epoch: 102, Loss: 0.072081
Epoch: 103, Loss: 0.068846
Epoch: 104, Loss: 0.065720
Epoch: 105, Loss: 0.062812
Epoch: 106, Loss: 0.060021
Epoch: 107, Loss: 0.057340
Epoch: 108, Loss: 0.054727
Epoch: 109, Loss: 0.052401
Epoch: 110, Loss: 0.049990
Epoch: 111, Loss: 0.047774
Epoch: 112, Loss: 0.045641
Epoch: 113, Loss: 0.043598
Epoch: 114, Loss: 0.041658
Epoch: 115, Loss: 0.039789
Epoch: 116, Loss: 0.038038
Epoch: 117, Loss: 0.036361
Epoch: 118, Loss: 0.034746
Epoch: 119, Loss: 0.033215
Epoch: 120, Loss: 0.031777
Epoch: 121, Loss: 0.030379
Epoch: 122, Loss: 0.029005
Epoch: 123, Loss: 0.027740
Epoch: 124, Loss: 0.026495
Epoch: 125, Loss: 0.025338
Epoch: 126, Loss: 0.024206
Epoch: 127, Loss: 0.023141
Epoch: 128, Loss: 0.022115
Epoch: 129, Loss: 0.021165
Epoch: 130, Loss: 0.020226
Epoch: 131, Loss: 0.019322
Epoch: 132, Loss: 0.018485
Epoch: 133, Loss: 0.017682
Epoch: 134, Loss: 0.016895
Epoch: 135, Loss: 0.016144
Epoch: 136, Loss: 0.015440
Epoch: 137, Loss: 0.014762
Epoch: 138, Loss: 0.014116
Epoch: 139, Loss: 0.013496
Epoch: 140, Loss: 0.012923
Epoch: 141, Loss: 0.012327
Epoch: 142, Loss: 0.011790
Epoch: 143, Loss: 0.011268
Epoch: 144, Loss: 0.010778
Epoch: 145, Loss: 0.010307
Epoch: 146, Loss: 0.009854
Epoch: 147, Loss: 0.009426
Epoch: 148, Loss: 0.009017
Epoch: 149, Loss: 0.008620
Epoch: 150, Loss: 0.008237
Epoch: 151, Loss: 0.007878
Epoch: 152, Loss: 0.007538
Epoch: 153, Loss: 0.007208
Epoch: 154, Loss: 0.006895
Epoch: 155, Loss: 0.006590
Epoch: 156, Loss: 0.006302
Epoch: 157, Loss: 0.006022
Epoch: 158, Loss: 0.005769
Epoch: 159, Loss: 0.005511
Epoch: 160, Loss: 0.005268
Epoch: 161, Loss: 0.005039
Epoch: 162, Loss: 0.004817
Epoch: 163, Loss: 0.004608
Epoch: 164, Loss: 0.004408
Epoch: 165, Loss: 0.004213
Epoch: 166, Loss: 0.004030
Epoch: 167, Loss: 0.003855
Epoch: 168, Loss: 0.003686
Epoch: 169, Loss: 0.003521
Epoch: 170, Loss: 0.003369
Epoch: 171, Loss: 0.003226
Epoch: 172, Loss: 0.003080
Epoch: 173, Loss: 0.002950
Epoch: 174, Loss: 0.002820
Epoch: 175, Loss: 0.002696
Epoch: 176, Loss: 0.002580
Epoch: 177, Loss: 0.002468
Epoch: 178, Loss: 0.002360
Epoch: 179, Loss: 0.002256
Epoch: 180, Loss: 0.002156
Epoch: 181, Loss: 0.002064
Epoch: 182, Loss: 0.001975
Epoch: 183, Loss: 0.001890
Epoch: 184, Loss: 0.001806
Epoch: 185, Loss: 0.001726
Epoch: 186, Loss: 0.001651
Epoch: 187, Loss: 0.001580
Epoch: 188, Loss: 0.001512
Epoch: 189, Loss: 0.001445
Epoch: 190, Loss: 0.001382
Epoch: 191, Loss: 0.001323
Epoch: 192, Loss: 0.001264
Epoch: 193, Loss: 0.001212
Epoch: 194, Loss: 0.001157
Epoch: 195, Loss: 0.001107
Epoch: 196, Loss: 0.001057
Epoch: 197, Loss: 0.001012
Epoch: 198, Loss: 0.000968
Epoch: 199, Loss: 0.000926
Epoch: 200, Loss: 0.000886

In [247]:
model.eval()
pred = model(text_to_index("Who wrote 'To Kill a Mockingbird'?" , vocab))

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not list

In [ ]:
print(pred)